import type { Tender } from '@/types'

export const mockTenders: Tender[] = [
  {
    tender_id: "tender-001",
    title: "Supply of Office Furniture for Government Department",
    description: "Provision of office furniture including desks, chairs, and storage units for a period of 24 months. The tender includes delivery, installation, and maintenance services.",
    buyer: "Dept. of Public Works",
    industry_category: "Supply & Delivery",
    province: "GP",
    closing_date: "2026-01-15",
    published_date: "2024-12-01",
    document_links: ["specifications.pdf", "terms.pdf"],
    source: "etenders.gov.za",
    source_url: "https://etenders.gov.za/tender-001",
    created_at: "2024-12-01T10:00:00Z"
  },
  {
    tender_id: "tender-002",
    title: "IT Infrastructure Upgrade Project",
    description: "Complete overhaul of IT infrastructure including network equipment, servers, and security systems for provincial government offices.",
    buyer: "Gauteng Provincial Government",
    industry_category: "ICT & Software",
    province: "GP",
    closing_date: "2025-12-12",
    published_date: "2024-12-05",
    document_links: ["technical_specs.pdf", "security_requirements.pdf"],
    source: "etenders.gov.za",
    source_url: "https://etenders.gov.za/tender-002",
    created_at: "2024-12-05T14:30:00Z"
  },
  {
    tender_id: "tender-003",
    title: "Security Services for Government Buildings",
    description: "24/7 security services including guarding, surveillance systems, and access control for government facilities in Cape Town.",
    buyer: "Western Cape Government",
    industry_category: "Security Services",
    province: "WC",
    closing_date: "2026-01-10",
    published_date: "2024-12-08",
    document_links: ["security_plan.pdf", "personnel_requirements.pdf"],
    source: "westerncape.gov.za",
    source_url: "https://westerncape.gov.za/tender-003",
    created_at: "2024-12-08T09:15:00Z"
  },
  {
    tender_id: "tender-004",
    title: "Road Construction and Maintenance",
    description: "Construction of 50km of provincial roads including resurfacing, drainage systems, and bridge maintenance in KwaZulu-Natal.",
    buyer: "KZN Department of Transport",
    industry_category: "Construction",
    province: "KZN",
    closing_date: "2026-03-01",
    published_date: "2024-12-10",
    document_links: ["road_design.pdf", "environmental_impact.pdf"],
    source: "kzn.gov.za",
    source_url: "https://kzn.gov.za/tender-004",
    created_at: "2024-12-10T11:45:00Z"
  },
  {
    tender_id: "tender-005",
    title: "Cleaning and Hygiene Services",
    description: "Professional cleaning and hygiene services for government hospitals and clinics in the Eastern Cape region.",
    buyer: "Eastern Cape Health Department",
    industry_category: "Cleaning & Hygiene",
    province: "EC",
    closing_date: "2026-01-25",
    published_date: "2024-12-12",
    document_links: ["cleaning_standards.pdf", "health_safety.pdf"],
    source: "ec.gov.za",
    source_url: "https://ec.gov.za/tender-005",
    created_at: "2024-12-12T16:20:00Z"
  },
  {
    tender_id: "tender-006",
    title: "Fleet Management and Vehicle Leasing",
    description: "Comprehensive fleet management services including vehicle leasing, maintenance, and fuel management for municipal operations.",
    buyer: "Johannesburg Municipality",
    industry_category: "Transport & Fleet",
    province: "GP",
    closing_date: "2026-01-18",
    published_date: "2024-12-14",
    document_links: ["fleet_specs.pdf", "maintenance_schedule.pdf"],
    source: "joburg.org.za",
    source_url: "https://joburg.org.za/tender-006",
    created_at: "2024-12-14T13:00:00Z"
  },
  {
    tender_id: "tender-007",
    title: "Catering Services for Government Events",
    description: "Catering services for government conferences, meetings, and official events including special dietary requirements and event management.",
    buyer: "National Treasury",
    industry_category: "Catering & Hospitality",
    province: "GP",
    closing_date: "2026-02-22",
    published_date: "2024-12-16",
    document_links: ["catering_menu.pdf", "event_schedule.pdf"],
    source: "treasury.gov.za",
    source_url: "https://treasury.gov.za/tender-007",
    created_at: "2024-12-16T10:30:00Z"
  },
  {
    tender_id: "tender-008",
    title: "Agricultural Equipment Supply",
    description: "Supply of agricultural equipment and machinery for emerging farmers in the Free State province including tractors, irrigation systems, and storage facilities.",
    buyer: "Free State Agriculture Department",
    industry_category: "Agriculture",
    province: "FS",
    closing_date: "2026-02-05",
    published_date: "2024-12-18",
    document_links: ["equipment_list.pdf", "technical_specs.pdf"],
    source: "fs.gov.za",
    source_url: "https://fs.gov.za/tender-008",
    created_at: "2024-12-18T15:45:00Z"
  }
]
